set-option -g prefix M-w
set-option -g extended-keys always
set-option -gw extended-keys-format csi-u

bind-key R source-file ~/.config/tmux/tmux.conf

bind-key -n C-S-t new-window -c "#{pane_current_path}"
bind-key -n M-l next-window
bind-key -n M-h previous-window

set-option -g status-style bold,fg='#ebdbb2',bg='#3c3836'
set-option -g status-interval 0
set-option -g status-keys emacs
