# ~/.bash_profile

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && [[ ! -f /dev/shm/bash_profile_startx ]]; then
    touch /dev/shm/bash_profile_startx 
    exec startx &>/dev/null
fi

source $HOME/.bashrc

